services:
  site-aimore:
    build: .
    restart: always
    container_name: portal-aimore
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"

      # HTTPS (principal e www)
      - "traefik.http.routers.site-aimore.rule=Host(`geaimore.com.br`) || Host(`www.geaimore.com.br`)"
      - "traefik.http.routers.site-aimore.entrypoints=websecure"
      - "traefik.http.routers.site-aimore.tls=true"
      - "traefik.http.routers.site-aimore.tls.certresolver=letsencrypt"

      # HTTP -> HTTPS (precisa de um roteador próprio na porta 80)
      - "traefik.http.routers.site-aimore-http.rule=Host(`geaimore.com.br`) || Host(`www.geaimore.com.br`)"
      - "traefik.http.routers.site-aimore-http.entrypoints=web"
      - "traefik.http.routers.site-aimore-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      - "traefik.http.services.site-aimore.loadbalancer.server.port=80"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    container_name: n8n-aimore
    networks:
      - dokploy-network
    environment:
      - N8N_HOST=n8n.geaimore.com.br
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.geaimore.com.br/
      - N8N_PROXY_HOPS=1
      - N8N_SECURE_COOKIE=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
    volumes:
      - n8n_dados:/home/node/.n8n
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.n8n-aimore.rule=Host(`n8n.geaimore.com.br`)"
      - "traefik.http.routers.n8n-aimore.entrypoints=websecure"
      - "traefik.http.routers.n8n-aimore.tls=true"
      - "traefik.http.routers.n8n-aimore.tls.certresolver=letsencrypt"

      - "traefik.http.routers.n8n-aimore-http.rule=Host(`n8n.geaimore.com.br`)"
      - "traefik.http.routers.n8n-aimore-http.entrypoints=web"
      - "traefik.http.routers.n8n-aimore-http.middlewares=redirect-to-https"

      - "traefik.http.services.n8n-aimore.loadbalancer.server.port=5678"

volumes:
  n8n_dados:

networks:
  dokploy-network:
    external: true
